import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame2(),
        ]),
      ),
    );
  }
}

class Frame2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 320,
          height: 568,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 12,
                top: 83,
                child: Container(
                  width: 295,
                  height: 534,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/295x534"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(62),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 83,
                child: Container(
                  width: 295,
                  height: 534,
                  decoration: ShapeDecoration(
                    color: Colors.black.withOpacity(0.4699999988079071),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(58),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 229,
                child: Text(
                  'Please type here',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 262,
                child: Container(
                  width: 242,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 242,
                          height: 47,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFBFBFB),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 0.50),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12,
                        top: 13,
                        child: Container(
                          width: 24,
                          height: 24,
                          padding: const EdgeInsets.symmetric(horizontal: 2.50, vertical: 4.50),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 19,
                                height: 15,
                                child: Stack(children: [
                                    ,
                                    ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63,
                        top: 17,
                        child: Text(
                          'Enter email',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.5),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 451,
                child: Container(
                  width: 236,
                  height: 35,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 84,
                        top: 0,
                        child: Container(
                          width: 152,
                          height: 35,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFBFBFB),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 0.50),
                              borderRadius: BorderRadius.circular(22),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 10,
                        child: Text(
                          ' PIN NUMBER',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.8600000143051147),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 145,
                        top: 10,
                        child: Text(
                          '0000',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.5),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 326,
                child: Container(
                  width: 242,
                  height: 107,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 242,
                          height: 47,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFBFBFB),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 0.50),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 15,
                        child: Container(
                          width: 21,
                          height: 19,
                          child: Stack(children: [
                              ,
                              ]),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 60,
                        child: Container(
                          width: 242,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 242,
                                  height: 47,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFBFBFB),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 0.50),
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 16,
                                child: Container(
                                  width: 21,
                                  height: 19,
                                  child: Stack(children: [
                                      ,
                                      ]),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 63,
                        top: 17,
                        child: Text(
                          'Enter  password',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.5),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 64,
                        top: 76,
                        child: Text(
                          'Re-type password',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.5),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 499,
                child: Container(
                  width: 242,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 95,
                        top: 11,
                        child: Text(
                          'ADD',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Castoro',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 199,
                child: SizedBox(
                  width: 77,
                  height: 31,
                  child: Text(
                    'Login',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF888888),
                      fontSize: 20,
                      fontFamily: 'Castoro',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 87,
                top: 8,
                child: Container(
                  width: 145,
                  height: 146,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/145x146"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(150),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 116,
                top: 199,
                child: Text(
                  '+ Admin',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Castoro',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}