import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame1(),
        ]),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 320,
          height: 568,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 12,
                top: 124,
                child: Container(
                  width: 295,
                  height: 527,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/295x527"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(62),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 12,
                top: 124,
                child: Container(
                  width: 295,
                  height: 484,
                  decoration: ShapeDecoration(
                    color: Colors.black.withOpacity(0.4699999988079071),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(58),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 200,
                top: 522,
                child: Text(
                  'Admin',
                  style: TextStyle(
                    color: Color(0xFF0367FF),
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                    decoration: TextDecoration.underline,
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 314,
                child: Container(
                  width: 242,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 242,
                          height: 47,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFFBFBFB),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(width: 0.50, color: Color(0xFFD5E2F6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12,
                        top: 13,
                        child: Container(
                          width: 24,
                          height: 24,
                          padding: const EdgeInsets.symmetric(horizontal: 2.50, vertical: 4.50),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 19,
                                height: 15,
                                child: const Stack(children: [
                                ]),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 377,
                child: Container(
                  width: 242,
                  height: 47,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 242,
                          height: 47,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFFBFBFB),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(width: 0.50, color: Color(0xFFD5E2F6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 15,
                        child: Container(
                          width: 21,
                          height: 19,
                          child: const Stack(children: [
                          ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 237,
                top: 392,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.symmetric(horizontal: 2, vertical: 4),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 20,
                        height: 16,
                        child: const Stack(children: [
                        ]),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 395,
                child: Text(
                  'Password',
                  style: TextStyle(
                    color: Colors.black.withOpacity(0.4099999964237213),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 331,
                child: Text(
                  'Email Address',
                  style: TextStyle(
                    color: Colors.black.withOpacity(0.4099999964237213),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              const Positioned(
                left: 40,
                top: 271,
                child: Text(
                  'Provide your credentials.',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              const Positioned(
                left: 29,
                top: 240,
                child: SizedBox(
                  width: 77,
                  height: 31,
                  child: Text(
                    'Login',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Castoro',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 134,
                top: 468,
                child: Text(
                  'Login',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 19,
                    fontFamily: 'Inder',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              const Positioned(
                left: 57,
                top: 527,
                child: Text(
                  'Do you want to add admin? Click',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 9,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 87,
                top: 49,
                child: Container(
                  width: 145,
                  height: 146,
                  decoration: ShapeDecoration(
                    image: const DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/145x146"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(150),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}